window.PORTFOLIO = {
  profile: {
    title: "陶瓷产品与文创设计作品集",
    subtitle: "Ceramic Product / Cultural Creative",
  },
  filters: [
    { id: "all", label: "全部" },
    { id: "product", label: "产品陶瓷" },
    { id: "visual", label: "视觉海报" },
    { id: "craft", label: "工艺实践" },
    { id: "sketch", label: "手绘推导" },
    { id: "model", label: "三维建模" },
  ],
  assets: [
    { id: "render-01", title: "荷叶盏延伸", type: "产品效果", tags: ["product"], thumb: "assets/thumbs/render-01.jpg", large: "assets/large/render-01.jpg" },
    { id: "render-02", title: "民族文化设计屏风", type: "产品效果", tags: ["product"], thumb: "assets/thumbs/render-02.jpg", large: "assets/large/render-02.jpg" },
    { id: "render-03", title: "茉莉花题材 1", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-03.jpg", large: "assets/large/render-03.jpg" },
    { id: "render-04", title: "茉莉花题材 2", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-04.jpg", large: "assets/large/render-04.jpg" },
    { id: "render-05", title: "茉莉花题材 3", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-05.jpg", large: "assets/large/render-05.jpg" },
    { id: "render-06", title: "清明上河图 1", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-06.jpg", large: "assets/large/render-06.jpg" },
    { id: "render-07", title: "清明上河图 2", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-07.jpg", large: "assets/large/render-07.jpg" },
    { id: "render-08", title: "清明上河图 3", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-08.jpg", large: "assets/large/render-08.jpg" },
    { id: "render-09", title: "清明上河图复古 1", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-09.jpg", large: "assets/large/render-09.jpg" },
    { id: "render-10", title: "清明上河图复古 2", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-10.jpg", large: "assets/large/render-10.jpg" },
    { id: "render-11", title: "清明上河图复古 3", type: "包装效果", tags: ["product"], thumb: "assets/thumbs/render-11.jpg", large: "assets/large/render-11.jpg" },
    { id: "poster-01", title: "春风海报 1", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-01.jpg", large: "assets/large/poster-01.jpg" },
    { id: "poster-02", title: "春风海报 2", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-02.jpg", large: "assets/large/poster-02.jpg" },
    { id: "poster-03", title: "二十四节气茶具", type: "产品海报", tags: ["product", "visual"], thumb: "assets/thumbs/poster-03.jpg", large: "assets/large/poster-03.jpg" },
    { id: "poster-04", title: "二十四节气海报 1", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-04.jpg", large: "assets/large/poster-04.jpg" },
    { id: "poster-05", title: "二十四节气海报 2", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-05.jpg", large: "assets/large/poster-05.jpg" },
    { id: "poster-06", title: "二十四节气海报 3", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-06.jpg", large: "assets/large/poster-06.jpg" },
    { id: "poster-07", title: "二十四节气海报 4", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-07.jpg", large: "assets/large/poster-07.jpg" },
    { id: "poster-08", title: "客家文化 IP 海报 1", type: "IP 视觉", tags: ["visual"], thumb: "assets/thumbs/poster-08.jpg", large: "assets/large/poster-08.jpg" },
    { id: "poster-09", title: "客家文化 IP 海报 2", type: "IP 视觉", tags: ["visual"], thumb: "assets/thumbs/poster-09.jpg", large: "assets/large/poster-09.jpg" },
    { id: "poster-10", title: "客家文化 IP 海报 3", type: "IP 视觉", tags: ["visual"], thumb: "assets/thumbs/poster-10.jpg", large: "assets/large/poster-10.jpg" },
    { id: "poster-11", title: "乐平戏茶具", type: "产品海报", tags: ["product", "visual"], thumb: "assets/thumbs/poster-11.jpg", large: "assets/large/poster-11.jpg" },
    { id: "poster-12", title: "青瓷序陶瓷元素提取", type: "设计推导", tags: ["visual", "sketch"], thumb: "assets/thumbs/poster-12.jpg", large: "assets/large/poster-12.jpg" },
    { id: "poster-13", title: "青花瓷陶瓷设计海报", type: "产品海报", tags: ["product", "visual"], thumb: "assets/thumbs/poster-13.jpg", large: "assets/large/poster-13.jpg" },
    { id: "poster-14", title: "人物海报设计 1", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-14.jpg", large: "assets/large/poster-14.jpg" },
    { id: "poster-15", title: "人物海报设计 2", type: "海报设计", tags: ["visual"], thumb: "assets/thumbs/poster-15.jpg", large: "assets/large/poster-15.jpg" },
    { id: "poster-16", title: "陶瓷制作流程海报", type: "流程海报", tags: ["visual", "craft"], thumb: "assets/thumbs/poster-16.jpg", large: "assets/large/poster-16.jpg" },
    { id: "poster-17", title: "星月夜饰品设计海报", type: "产品海报", tags: ["product", "visual"], thumb: "assets/thumbs/poster-17.jpg", large: "assets/large/poster-17.jpg" },
    { id: "model-01", title: "产品 1", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-01.jpg", large: "assets/large/model-01.jpg" },
    { id: "model-02", title: "产品 2", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-02.jpg", large: "assets/large/model-02.jpg" },
    { id: "model-03", title: "产品 3", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-03.jpg", large: "assets/large/model-03.jpg" },
    { id: "model-04", title: "产品 4", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-04.jpg", large: "assets/large/model-04.jpg" },
    { id: "model-05", title: "产品 5", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-05.jpg", large: "assets/large/model-05.jpg" },
    { id: "model-06", title: "产品 6", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-06.jpg", large: "assets/large/model-06.jpg" },
    { id: "model-07", title: "产品 7", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-07.jpg", large: "assets/large/model-07.jpg" },
    { id: "model-08", title: "产品 8", type: "三维建模", tags: ["model"], thumb: "assets/thumbs/model-08.jpg", large: "assets/large/model-08.jpg" },
    { id: "model-09", title: "东南西北山水主题餐具 1", type: "三维建模", tags: ["model", "product"], thumb: "assets/thumbs/model-09.jpg", large: "assets/large/model-09.jpg" },
    { id: "model-10", title: "东南西北山水主题餐具 2", type: "三维建模", tags: ["model", "product"], thumb: "assets/thumbs/model-10.jpg", large: "assets/large/model-10.jpg" },
    { id: "model-11", title: "排水系统 1", type: "三维建模", tags: ["model", "product"], thumb: "assets/thumbs/model-11.jpg", large: "assets/large/model-11.jpg" },
    { id: "model-12", title: "排水系统 2", type: "三维建模", tags: ["model", "product"], thumb: "assets/thumbs/model-12.jpg", large: "assets/large/model-12.jpg" },
    { id: "model-13", title: "青铜器题材", type: "三维建模", tags: ["model", "product"], thumb: "assets/thumbs/model-13.jpg", large: "assets/large/model-13.jpg" },
    { id: "model-14", title: "四季山水陶瓷茶具", type: "三维建模", tags: ["model", "product"], thumb: "assets/thumbs/model-14.jpg", large: "assets/large/model-14.jpg" },
    { id: "model-15", title: "壮锦提取 1", type: "三维建模", tags: ["model", "sketch"], thumb: "assets/thumbs/model-15.jpg", large: "assets/large/model-15.jpg" },
    { id: "craft-01", title: "绘画作品：青花兔兔昂", type: "手工绘制", tags: ["craft"], thumb: "assets/thumbs/craft-01.jpg", large: "assets/large/craft-01.jpg" },
    { id: "craft-02", title: "陶瓷粉彩 1", type: "手工绘制", tags: ["craft"], thumb: "assets/thumbs/craft-02.jpg", large: "assets/large/craft-02.jpg" },
    { id: "craft-03", title: "陶瓷粉彩 2", type: "手工绘制", tags: ["craft"], thumb: "assets/thumbs/craft-03.jpg", large: "assets/large/craft-03.jpg" },
    { id: "craft-04", title: "客人订制：釉下彩", type: "手工绘制", tags: ["craft"], thumb: "assets/thumbs/craft-04.jpg", large: "assets/large/craft-04.jpg" },
    { id: "craft-05", title: "烧成工艺作品展示", type: "工艺实践", tags: ["craft"], thumb: "assets/thumbs/craft-05.jpg", large: "assets/large/craft-05.jpg" },
    { id: "craft-06", title: "包装设计手工模型", type: "手工模型", tags: ["craft", "product"], thumb: "assets/thumbs/craft-06.jpg", large: "assets/large/craft-06.jpg" },
    { id: "craft-07", title: "陶瓷饰品设计 1", type: "手工作品", tags: ["craft", "product"], thumb: "assets/thumbs/craft-07.jpg", large: "assets/large/craft-07.jpg" },
    { id: "craft-08", title: "陶瓷饰品设计 2", type: "手工作品", tags: ["craft", "product"], thumb: "assets/thumbs/craft-08.jpg", large: "assets/large/craft-08.jpg" },
    { id: "craft-09", title: "陶瓷贴花设计", type: "手工作品", tags: ["craft", "product"], thumb: "assets/thumbs/craft-09.jpg", large: "assets/large/craft-09.jpg" },
    { id: "craft-10", title: "窑体手工模型 1", type: "手工模型", tags: ["craft"], thumb: "assets/thumbs/craft-10.jpg", large: "assets/large/craft-10.jpg" },
    { id: "craft-11", title: "窑体手工模型 2", type: "手工模型", tags: ["craft"], thumb: "assets/thumbs/craft-11.jpg", large: "assets/large/craft-11.jpg" },
    { id: "craft-12", title: "陶瓷科技渗水系统 1", type: "系统设计", tags: ["craft", "product"], thumb: "assets/thumbs/craft-12.jpg", large: "assets/large/craft-12.jpg" },
    { id: "craft-13", title: "陶瓷科技渗水系统 2", type: "系统设计", tags: ["craft", "product"], thumb: "assets/thumbs/craft-13.jpg", large: "assets/large/craft-13.jpg" },
    { id: "sketch-01", title: "壮锦提取 2", type: "元素提取", tags: ["sketch"], thumb: "assets/thumbs/sketch-01.jpg", large: "assets/large/sketch-01.jpg" },
    { id: "sketch-02", title: "器型结构草图", type: "手绘推导", tags: ["sketch"], thumb: "assets/thumbs/sketch-02.jpg", large: "assets/large/sketch-02.jpg" },
    { id: "sketch-03", title: "陶瓷器型手绘", type: "手绘推导", tags: ["sketch"], thumb: "assets/thumbs/sketch-03.jpg", large: "assets/large/sketch-03.jpg" },
    { id: "sketch-04", title: "荷风青韵设计版", type: "手绘推导", tags: ["sketch", "product"], thumb: "assets/thumbs/sketch-04.jpg", large: "assets/large/sketch-04.jpg" },
    { id: "sketch-05", title: "组合器型草图", type: "手绘推导", tags: ["sketch"], thumb: "assets/thumbs/sketch-05.jpg", large: "assets/large/sketch-05.jpg" },
    { id: "sketch-06", title: "山水茶具草图", type: "手绘推导", tags: ["sketch", "product"], thumb: "assets/thumbs/sketch-06.jpg", large: "assets/large/sketch-06.jpg" },
    { id: "sketch-07", title: "丝丝入叶手绘方案", type: "手绘推导", tags: ["sketch", "product"], thumb: "assets/thumbs/sketch-07.jpg", large: "assets/large/sketch-07.jpg" },
    { id: "sketch-08", title: "山水纹样方案", type: "手绘推导", tags: ["sketch", "product"], thumb: "assets/thumbs/sketch-08.jpg", large: "assets/large/sketch-08.jpg" },
    { id: "sketch-09", title: "饰品草图", type: "手绘推导", tags: ["sketch", "product"], thumb: "assets/thumbs/sketch-09.jpg", large: "assets/large/sketch-09.jpg" },
    { id: "sketch-10", title: "图形标志草案", type: "手绘推导", tags: ["sketch", "visual"], thumb: "assets/thumbs/sketch-10.jpg", large: "assets/large/sketch-10.jpg" },
  ],
  projects: [
    {
      id: "qingming",
      title: "清明上河图茶礼系列",
      type: "产品包装 / 茶具陈列",
      year: "2025",
      tags: ["传统图像", "礼盒设计", "产品效果"],
      cover: "render-06",
      images: ["render-06", "render-07", "render-08", "render-09", "render-10", "render-11"],
      summary: "将《清明上河图》的长卷叙事转化为茶礼包装纹样与器物陈列，强调复古色系、礼盒层次和产品氛围。",
    },
    {
      id: "jasmine",
      title: "茉莉花题材包装设计",
      type: "包装设计 / 产品效果",
      year: "2025",
      tags: ["花卉元素", "礼盒", "清雅色调"],
      cover: "render-04",
      images: ["render-03", "render-04", "render-05"],
      summary: "以茉莉花的形态与香气联想组织包装视觉，使用浅色留白、植物光影和开盒陈列增强产品质感。",
    },
    {
      id: "hakka-ip",
      title: "客家文化 IP 视觉",
      type: "文化 IP / 视觉系统",
      year: "2024",
      tags: ["角色设计", "地域文化", "视觉延展"],
      cover: "poster-08",
      images: ["poster-08", "poster-09", "poster-10"],
      summary: "以客家文化为主题进行角色与周边视觉延展，包含角色表情、服饰元素、色彩规范与应用展示。",
    },
    {
      id: "solar-terms",
      title: "二十四节气茶具与海报",
      type: "产品概念 / 海报设计",
      year: "2024",
      tags: ["节气", "茶具", "东方视觉"],
      cover: "poster-03",
      images: ["poster-03", "poster-04", "poster-05", "poster-06", "poster-07"],
      summary: "围绕节气意象展开茶具与海报表达，将山水、植物和节令文字转化为系列化视觉语言。",
    },
    {
      id: "qingci",
      title: "青瓷序陶瓷元素提取",
      type: "元素提取 / 海报版式",
      year: "2024",
      tags: ["青瓷", "纹样提取", "版式"],
      cover: "poster-12",
      images: ["poster-12", "sketch-01", "model-15"],
      summary: "从青瓷造型与壮锦纹样中提取结构元素，用于纹样、器型与展示版面的组合推导。",
    },
    {
      id: "mountain-tableware",
      title: "山水主题餐具建模",
      type: "三维建模 / 餐具系列",
      year: "2024",
      tags: ["Rhino/建模", "茶具", "山水纹样"],
      cover: "model-10",
      images: ["model-09", "model-10", "model-14", "sketch-06", "sketch-08"],
      summary: "以山水意象组织餐具器型与纹样，包含手绘推导、建模成组和最终产品陈列效果。",
    },
    {
      id: "water-system",
      title: "陶瓷科技渗水系统",
      type: "系统设计 / 展示板",
      year: "2025",
      tags: ["系统设计", "模型", "展示板"],
      cover: "craft-12",
      images: ["craft-12", "craft-13", "model-11", "model-12", "poster-16"],
      summary: "结合陶瓷材料与公共空间排水场景，呈现结构模型、应用场景和展示板信息组织。",
    },
    {
      id: "starry-jewelry",
      title: "星月夜饰品设计",
      type: "饰品设计 / 手工制作",
      year: "2024",
      tags: ["饰品", "陶瓷", "手工"],
      cover: "poster-17",
      images: ["poster-17", "craft-07", "craft-08", "sketch-09", "model-08"],
      summary: "从星月夜色彩与形态中发展陶瓷饰品方案，包含草图、建模、实物组合与最终展示海报。",
    },
  ],
};
